# Production environment values

# Higher replicas for production
replicaCount: 5

# Image configuration
image:
  repository: grooveshop/recommendation-engine
  pullPolicy: Always
  tag: "1.0.0"  # Use specific version tags in production

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "200"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.example.com"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: recommendations.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: recommendation-engine-tls
      hosts:
        - recommendations.example.com

# Production resource limits
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# Enabled autoscaling for production
autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 30
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # More conservative scale-down
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 5
        periodSeconds: 15

# Production configuration
config:
  logLevel: "info"
  rustBacktrace: "0"

  # Algorithm weights
  collaborativeWeight: "0.6"
  contentWeight: "0.4"

  # Production cache TTLs
  cacheTtlRecommendations: "300"  # 5 minutes
  cacheTtlTrending: "3600"        # 1 hour
  cacheTtlUserProfile: "600"      # 10 minutes

  # Rate limiting
  rateLimitRequests: "1000"
  rateLimitWindowSecs: "60"

  # Model update intervals
  updateIntervalUserSimilarity: "10"
  updateIntervalEntitySimilarity: "5"
  updateIntervalTrending: "3600"
  fullRebuildInterval: "86400"    # 24 hours

  # Recommendation parameters
  defaultRecommendationCount: "10"
  similarityThreshold: "0.3"
  coldStartMinInteractions: "5"

  # Larger database pools for production
  dbPoolMaxConnections: "30"
  dbPoolMinConnections: "10"
  redisPoolMaxConnections: "20"

  # Feature extraction
  maxAttributeDepth: "3"
  vectorDimension: "128"

# Pod anti-affinity for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - recommendation-engine
        topologyKey: kubernetes.io/hostname

# Secrets should be provided via external secret management (e.g., Sealed Secrets, External Secrets Operator)
secrets:
  databaseUrl: ""  # Managed by external secret system
  redisUrl: ""     # Managed by external secret system
  apiKey: ""       # Managed by external secret system
