# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
version = 2
ignore = []
# Warn for all advisory severities
severity-threshold = "low"

[licenses]
version = 2
# Allow these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8

# Deny these licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# Skip duplicate version check for these crates
skip = []

# Skip trees with these crates
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
github = ["anthropics", "grooveshop"]
